'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowLeft,ArrowUpRight,Box,Clock3,Download,History,IndianRupee,Store,Truck} from 'lucide-react';
import {AREAS,currentRevenue,DEMO_MONTH,deliveryEstimate,exportAreaCsv,inr,number,PHASES,rateProjection,type Area} from './model';
import {usePartner} from './provider';
import {Metric,DeliveryCalculation,downloadCsv} from './shared';
import {FeeEditor} from './fee-editor';
import {RevenueChart} from './revenue-chart';
import {CoverageMap} from './coverage-map';
export function AreaDetail({area}:{area:Area}) {
 const {data,ready}=usePartner(),[average,setAverage]=useState<'weekly'|'monthly'>('monthly');const rates=data.rates[area.id],revenue=currentRevenue(area),estimate=deliveryEstimate(revenue,area.boxes),projection=rateProjection(rates,area.boxes),history=data.changes.filter(c=>c.areaId===area.id).slice(0,5);
 return <><Link className="dp-back" href="/partner/cities/pune"><ArrowLeft size={16}/>Pune overview</Link><div className="dp-heading"><div><div className="dp-eyebrow">AREA ECONOMICS · PUNE</div><h1>{area.name}<span>.</span></h1><p>{area.description}</p></div><button className="dp-secondary" disabled={!ready} onClick={()=>downloadCsv(`motion-${area.id}-partner-report.csv`,exportAreaCsv(area,rates))}><Download size={16}/>Export report</button></div><div className="dp-area-tabs" aria-label="Switch area">{AREAS.map(a=><Link key={a.id} className={a.id===area.id?'active':''} aria-current={a.id===area.id?'page':undefined} href={`/partner/cities/pune/areas/${a.id}`}>{a.name}{a.id===area.id&&<ArrowUpRight size={14}/>}</Link>)}<span>{DEMO_MONTH} · Demo</span></div>
 <FeeEditor key={area.id} area={area}/>
 <div className="dp-section-title"><div><div className="dp-section-kicker">AREA PERFORMANCE</div><h2>Your neighbourhood, by the numbers.</h2></div><label className="dp-sort">Box averages<select aria-label="Box average sampling period" value={average} onChange={e=>setAverage(e.target.value as 'weekly'|'monthly')}><option value="monthly">Monthly sample</option><option value="weekly">Weekly sample</option></select></label></div>
 <div className="dp-metrics"><Metric label="Partner restaurants" value={number(area.restaurants)} note="Sample restaurant locations" icon={Store}/><Metric label="Average active boxes" value={number(average==='monthly'?area.averageMonthly:area.averageWeekly,1)} note={`${average==='monthly'?'Monthly':'Weekly'} sample · ${area.boxes} current boxes`} icon={Box}/><Metric label="Monthly ad revenue" value={inr(revenue)} note="Simulated partner earnings" icon={IndianRupee} accent/><Metric label="Est. earnings / delivery" value={inr(estimate.perDelivery,2)} note="30-day delivery model" icon={Truck}/></div>
 <div className="dp-area-analysis"><RevenueChart values={area.revenues}/><div className="dp-area-aside"><section className="dp-projection"><div className="dp-row-between"><span className="dp-section-kicker">PRICING SCENARIO</span><Clock3 size={19}/></div><h2>What your rates could earn.</h2><div className="dp-projection-amount">{inr(projection.fleetDay)}<span>per day across {area.boxes} boxes</span></div><dl><div><dt>Per box / day</dt><dd>{inr(projection.perBoxDay)}</dd></div><div><dt>All boxes / 30 days</dt><dd>{inr(projection.fleetMonth)}</dd></div></dl><p>Assumes all {area.boxes} boxes are booked for all 12 listed hours daily. This is a full-capacity scenario, not forecast revenue or profit.</p></section><DeliveryCalculation revenue={revenue} boxes={area.boxes}/></div></div>
 <div className="dp-bottom-grid"><section className="dp-panel"><div className="dp-panel-head"><div><h2>Where your boxes operate</h2><p>{area.name} · Pune</p></div><span className="dp-count">{area.boxes} boxes</span></div><CoverageMap selected={area.id}/></section><section className="dp-panel dp-history"><div className="dp-panel-head"><div><h2>Recent fee changes</h2><p>Saved locally · last 5 changes for this area</p></div><History size={19}/></div>{history.length?<ol>{history.map(c=><li key={c.id}><span className="dp-history-dot"/><div><b>Day-phase fees updated</b><time dateTime={c.savedAt}>{new Date(c.savedAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'})} IST</time><p>{PHASES.filter(p=>c.previous[p.id]!==c.next[p.id]).map(p=>`${p.name}: ${inr(c.previous[p.id],2)} → ${inr(c.next[p.id],2)}`).join(' · ')}</p></div></li>)}</ol>:<div className="dp-empty"><History size={28}/><h3>No fee changes yet</h3><p>Save a change above to start your local activity history.</p></div>}</section></div>
 </>;
}
