'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowLeft,ArrowUpRight,Box,Download,IndianRupee,Search,Store,Truck} from 'lucide-react';
import {AREAS,aggregateAreas,currentRevenue,DEMO_MONTH,deliveryEstimate,inr,number,csvCell} from './model';
import {Metric,DeliveryCalculation,downloadCsv} from './shared';
import {RevenueChart} from './revenue-chart';
import {CoverageMap} from './coverage-map';
export function CityOverview() {
 const stats=aggregateAreas(AREAS),[query,setQuery]=useState(''),[sort,setSort]=useState('revenue');
 const shown=AREAS.filter(a=>a.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):currentRevenue(b)-currentRevenue(a));
 const download=()=>{const rows=[['City','Area','Restaurants','Current boxes','Monthly average boxes','October 2026 simulated revenue INR','Estimated INR per delivery'],...AREAS.map(a=>['Pune',a.name,a.restaurants,a.boxes,a.averageMonthly,currentRevenue(a),deliveryEstimate(currentRevenue(a),a.boxes).perDelivery.toFixed(2)]),['SIMULATED DATA: delivery model uses 17 deliveries per box per day for 30 days.']];downloadCsv('motion-pune-partner-report.csv',rows.map(r=>r.map(csvCell).join(',')).join('\r\n'));};
 return <><Link className="dp-back" href="/partner"><ArrowLeft size={16}/>All cities</Link><div className="dp-heading"><div><div className="dp-eyebrow">CITY OVERVIEW · MAHARASHTRA</div><h1>Pune, in motion<span>.</span></h1><p>The bigger picture of your delivery network.</p></div><button className="dp-secondary" onClick={download}><Download size={16}/>Export report</button></div><div className="dp-subheading"><span className="dp-status"><i/>3 operating areas</span><span>{DEMO_MONTH} · Simulated data</span></div>
 <div className="dp-metrics"><Metric label="Partner restaurants" value={number(stats.restaurants)} note="Total across all 3 areas" icon={Store}/><Metric label="Advert boxes" value={number(stats.boxes)} note="Current count across the city" icon={Box}/><Metric label="Monthly ad revenue" value={inr(stats.revenue)} note="Sum of area ad earnings" icon={IndianRupee} accent/><Metric label="Est. earnings / delivery" value={inr(stats.perDelivery,2)} note="City revenue ÷ model deliveries" icon={Truck}/></div>
 <div className="dp-city-analysis"><RevenueChart values={stats.revenues}/><section className="dp-panel dp-coverage-panel"><div className="dp-panel-head"><div><h2>Your city coverage</h2><p>Explore any of your three areas</p></div><span className="dp-count">PUNE</span></div><CoverageMap/><div className="dp-average-note"><b>{number(stats.averageMonthly,1)} <span>average active boxes</span></b><small>Sum of area monthly averages · sample data</small></div></section></div>
 <section className="dp-panel dp-areas-panel"><div className="dp-panel-head"><div><h2>Area performance</h2><p>Open an area to manage fees and see its economics.</p></div><span className="dp-count">3 areas</span></div><div className="dp-toolbar"><label className="dp-search"><Search size={17}/><input aria-label="Search areas" placeholder="Search an area" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="dp-sort">Sort by<select aria-label="Sort areas" value={sort} onChange={e=>setSort(e.target.value)}><option value="revenue">Highest revenue</option><option value="name">Area name</option></select></label></div><div className="dp-table-scroll"><table className="dp-table dp-area-table"><caption className="sr-only">Pune area performance</caption><thead><tr><th>Area</th><th>Restaurants</th><th>Boxes</th><th>Monthly ad revenue</th><th>Est. / delivery</th><th><span className="sr-only">Open area</span></th></tr></thead><tbody>{shown.map(a=><tr key={a.id}><td><Link href={`/partner/cities/pune/areas/${a.id}`}><span className="dp-area-initial">{a.name[0]}</span><span><b>{a.name}</b><small>{a.description}</small></span></Link></td><td>{a.restaurants}</td><td>{a.boxes}</td><td><b>{inr(currentRevenue(a))}</b></td><td>{inr(deliveryEstimate(currentRevenue(a),a.boxes).perDelivery,2)}</td><td><Link className="dp-icon-button" href={`/partner/cities/pune/areas/${a.id}`} aria-label={`View ${a.name} economics`}><ArrowUpRight size={18}/></Link></td></tr>)}</tbody></table></div>{!shown.length&&<div className="dp-empty"><h3>No matching areas</h3><p>Try another area name.</p><button className="dp-secondary" onClick={()=>setQuery('')}>Clear search</button></div>}</section><DeliveryCalculation revenue={stats.revenue} boxes={stats.boxes} compact/>
 </>;
}
