'use client';
import {useRef,useState} from 'react';
import {ArrowRight,Check,Info,Loader2,PencilLine,Sun,Sunset,Moon} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {PHASES,inr,rateProjection,validateRates,type Area,type RateDraft,type Rates} from './model';
import {usePartner} from './provider';
const icons={morning:Sun,afternoon:Sunset,night:Moon};
export function FeeEditor({area}:{area:Area}) {
 const {data,ready,storageError,save}=usePartner();const rates=data.rates[area.id];
 const [open,setOpen]=useState(false),[draft,setDraft]=useState<RateDraft>({morning:'',afternoon:'',night:''}),[error,setError]=useState(''),[fieldErrors,setFieldErrors]=useState<Partial<Record<keyof Rates,string>>>({}),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
 const lock=useRef(false), projection=rateProjection(rates,area.boxes);
 const edited=PHASES.some(p=>Number(draft[p.id])!==rates[p.id]);
 const show=()=>{setDraft({morning:String(rates.morning),afternoon:String(rates.afternoon),night:String(rates.night)});setError('');setFieldErrors({});setSaved(false);setOpen(true);};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(lock.current)return;const result=validateRates(draft);setFieldErrors(result.errors);if(!result.values)return;lock.current=true;setSaving(true);setError('');try{await save(area.id,result.values);setOpen(false);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Could not save fees.');}finally{setSaving(false);lock.current=false;}};
 const preview=validateRates(draft).values;
 return <section className="dp-panel dp-fees"><div className="dp-panel-head"><div><div className="dp-section-kicker">MONETARY CONTROL</div><h2>Set the value of your hours.</h2><p>Day-phase pricing for {area.name}</p></div><button className="dp-primary" disabled={!ready||!!storageError} onClick={show}><PencilLine size={15}/>Modify fees</button></div>
 {saved&&<div className="dp-inline-success" role="status"><Check size={16}/>Fees saved in this browser. Your pricing table is up to date.</div>}
 <div className="dp-table-scroll"><table className="dp-table dp-fees-table"><caption className="sr-only">Day-phase fees for {area.name}</caption><thead><tr><th>Day phase</th><th>Window · IST</th><th>Hours</th><th>Fee / box / hour</th><th>Per box / day</th></tr></thead><tbody>{PHASES.map(p=>{const Icon=icons[p.id];return <tr key={p.id}><td><span className={'dp-phase-icon '+p.id}><Icon size={18}/></span><b>{p.name}</b></td><td>{p.time}</td><td>{p.hours} hrs</td><td className="dp-rate-value">{inr(rates[p.id],2)}</td><td>{inr(rates[p.id]*p.hours,2)}</td></tr>;})}</tbody><tfoot><tr><td colSpan={3}>12 scheduled hours per box</td><td>Daily rate total</td><td>{inr(projection.perBoxDay,2)}</td></tr></tfoot></table></div>
 <div className="dp-fee-foot"><Info size={16}/><p>Rates are per advert box per hour. Unlisted hours are excluded. Changes apply to future demo quotes; historical revenue stays unchanged.</p></div>
 <Dialog open={open} onOpenChange={v=>{if(!saving)setOpen(v);}}><DialogContent className="dp-fee-dialog"><DialogHeader><DialogTitle>Modify fees · {area.name}</DialogTitle><DialogDescription>Set the INR rate per box-hour for each day phase. This updates local demo pricing only.</DialogDescription></DialogHeader><form onSubmit={submit} noValidate><div className="dp-editor-head"><span>Day phase · IST</span><span>Fee / box / hour</span></div>{PHASES.map(p=>{const Icon=icons[p.id];return <div className="dp-edit-row" key={p.id}><label htmlFor={'fee-'+p.id}><Icon size={19}/><span><b>{p.name}</b><small>{p.time}</small></span></label><div><div className={'dp-money-input '+(fieldErrors[p.id]?'has-error':'')}><span>₹</span><input id={'fee-'+p.id} aria-label={`${p.name} fee per box per hour`} aria-invalid={!!fieldErrors[p.id]} aria-describedby={fieldErrors[p.id]?`error-${p.id}`:undefined} type="number" min="0" max="10000" step="0.01" inputMode="decimal" value={draft[p.id]} onChange={e=>{setDraft(d=>({...d,[p.id]:e.target.value}));setFieldErrors(s=>({...s,[p.id]:undefined}));setError('');}}/></div>{fieldErrors[p.id]&&<p role="alert" className="dp-field-error" id={`error-${p.id}`}>{fieldErrors[p.id]}</p>}</div></div>;})}<div className="dp-editor-summary"><span>Daily fee per box</span><strong>{inr(projection.perBoxDay,2)}<ArrowRight size={16}/>{preview?inr(rateProjection(preview,area.boxes).perBoxDay,2):'—'}</strong></div>{error&&<p className="dp-error" role="alert">{error}</p>}<div className="dp-dialog-actions"><button className="dp-secondary" type="button" disabled={saving} onClick={()=>setOpen(false)}>Cancel</button><button className="dp-primary" type="submit" disabled={saving||!edited}>{saving?<Loader2 className="dp-spin" size={16}/>:<Check size={16}/>}Save changes</button></div></form></DialogContent></Dialog>
 </section>;
}
