'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Box,Building2,IndianRupee,MapPin,Search,Store,Truck} from 'lucide-react';
import {AREAS,aggregateAreas,DEMO_MONTH,inr,number} from './model';
import {Metric} from './shared';
export function PartnerHome() {
 const [query,setQuery]=useState('');const stats=aggregateAreas(AREAS);const show='pune maharashtra'.includes(query.trim().toLowerCase());
 return <><div className="dp-heading"><div><div className="dp-eyebrow">YOUR PARTNER WORKSPACE</div><h1>Your network. More possibilities<span>.</span></h1><p>Turn everyday deliveries into a new source of income.</p></div><span className="dp-period"><i/>{DEMO_MONTH}</span></div>
 <div className="dp-metrics"><Metric label="Cities in your network" value="01" note="Pune, Maharashtra" icon={Building2}/><Metric label="Advert boxes" value={number(stats.boxes)} note="Across 3 operating areas" icon={Box}/><Metric label="Partner restaurants" value={number(stats.restaurants)} note="Unique sample locations" icon={Store}/><Metric label="Monthly ad revenue" value={inr(stats.revenue)} note="Simulated partner earnings" icon={IndianRupee} accent/></div>
 <div className="dp-home-grid"><section className="dp-panel dp-cities"><div className="dp-panel-head"><div><h2>Your cities</h2><p>Choose a city to explore performance and pricing.</p></div><span className="dp-count">1 city</span></div><label className="dp-search"><Search size={17}/><input aria-label="Search cities" placeholder="Search city or state" value={query} onChange={e=>setQuery(e.target.value)}/></label>{show?<Link href="/partner/cities/pune" className="dp-city-card"><div className="dp-city-art" aria-hidden="true"><div className="dp-skyline"><i/><i/><i/><i/><i/><i/><i/></div><span>PUNE</span><MapPin size={26}/></div><div className="dp-city-body"><div className="dp-row-between"><div><small>MAHARASHTRA · WEST INDIA</small><h3>Pune</h3></div><span className="dp-status"><i/>Operating</span></div><p>Three neighbourhoods. One connected network.</p><div className="dp-city-metrics"><span><b>3</b>Areas</span><span><b>{stats.boxes}</b>Boxes</span><span><b>{stats.restaurants}</b>Restaurants</span></div><div className="dp-city-bottom"><span>Explore city operations</span><ArrowUpRight size={20}/></div></div></Link>:<div className="dp-empty"><Search size={28}/><h3>No cities found</h3><p>Try searching for Pune or Maharashtra.</p><button className="dp-secondary" onClick={()=>setQuery('')}>Clear search</button></div>}</section>
 <aside className="dp-opportunity"><div className="dp-opportunity-icon"><Truck size={27}/></div><span className="dp-eyebrow">BUILT AROUND YOUR ROUTES</span><h2>Small screens.<br/>New opportunities.</h2><p>See what your network earns and set hourly rates that work for each neighbourhood.</p><ol><li><span>01</span><div><b>Explore your city</b><small>Restaurants, boxes and revenue in one place.</small></div></li><li><span>02</span><div><b>Understand each area</b><small>Follow monthly performance and estimates.</small></div></li><li><span>03</span><div><b>Manage your fees</b><small>Adjust morning, afternoon and night rates.</small></div></li></ol><Link href="/partner/cities/pune">Open Pune overview<ArrowRight size={18}/></Link></aside></div>
 </>;
}
