'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {ArrowUpRight,Building2,ChevronRight,Headphones,Info,LayoutDashboard,MapPin,Menu,Radio,Truck} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {PartnerProvider,usePartner} from './provider';
import {AREAS} from './model';
function Navigation({close}:{close:()=>void}) {
 const path=usePathname();return <><Link className="dp-brand" href="/partner" onClick={close}><span>m</span>motion<i>.</i></Link><div className="dp-nav-caption">DELIVERY PARTNER</div><nav aria-label="Delivery partner navigation"><Link href="/partner" className={'dp-nav-link '+(path==='/partner'?'active':'')} aria-current={path==='/partner'?'page':undefined} onClick={close}><LayoutDashboard size={18}/>Overview{path==='/partner'&&<ChevronRight size={15}/>}</Link><Link href="/partner/cities/pune" className={'dp-nav-link '+(path.startsWith('/partner/cities')?'active':'')} aria-current={path==='/partner/cities/pune'?'page':undefined} onClick={close}><Building2 size={18}/>Pune operations{path.startsWith('/partner/cities')&&<ChevronRight size={15}/>}</Link>{path.startsWith('/partner/cities')&&<div className="dp-area-nav">{AREAS.map(a=><Link key={a.id} href={`/partner/cities/pune/areas/${a.id}`} className={path.endsWith('/'+a.id)?'selected':''} aria-current={path.endsWith('/'+a.id)?'page':undefined} onClick={close}><i/>{a.name}</Link>)}</div>}<div className="dp-nav-divider"/><Link href="/" className="dp-nav-link dp-switch" onClick={close}><ArrowUpRight size={18}/>Advertiser workspace</Link></nav><div className="dp-sidebar-bottom"><div className="dp-sidebar-card"><Radio size={19}/><b>Every route. More value.</b><p>Your delivery network, with a new source of revenue.</p></div><div className="dp-profile"><span>DP</span><div><b>Delivery partner</b><small>Demo organisation</small></div></div></div></>;
}
function Inner({children}:{children:React.ReactNode}) {
 const path=usePathname(),[mobile,setMobile]=useState(false),[help,setHelp]=useState(false);const {storageError}=usePartner();
 const area=AREAS.find(a=>path.endsWith('/areas/'+a.id));
 return <div className="dp-app"><aside className="dp-sidebar"><Navigation close={()=>{}}/></aside><div className="dp-main"><header className="dp-topbar"><div className="dp-breadcrumb"><button className="dp-icon-button dp-mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={20}/></button><Link href="/partner">Workspace</Link><ChevronRight size={14}/>{path==='/partner'?<b>Overview</b>:<><Link href="/partner/cities/pune">Pune</Link>{area&&<><ChevronRight size={14}/><b>{area.name}</b></>}</>}</div><div className="dp-topbar-right"><span><MapPin size={14}/>India</span><span className="dp-demo-badge">Partner demo</span><button className="dp-icon-button" aria-label="About this demo" onClick={()=>setHelp(true)}><Headphones size={18}/></button><span className="dp-avatar">DP</span></div></header><main className="dp-content"><div className="dp-demo-note"><Info size={14}/><span>Simulated operations and earnings. Fee changes are saved only in this browser.</span></div>{storageError&&<div className="dp-error" role="alert">{storageError}</div>}{children}<footer className="dp-footer"><b>motion<span>.</span></b><span>Built for partners on the move.</span><small>Frontend prototype</small></footer></main></div>
 <Dialog open={mobile} onOpenChange={setMobile}><DialogContent className="dp-mobile-drawer"><DialogHeader className="sr-only"><DialogTitle>Delivery partner navigation</DialogTitle><DialogDescription>Choose a workspace or area.</DialogDescription></DialogHeader><Navigation close={()=>setMobile(false)}/></DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="dp-help-dialog"><DialogHeader><DialogTitle>Welcome to the partner demo</DialogTitle><DialogDescription>Explore your city, review area economics, and try day-phase pricing.</DialogDescription></DialogHeader><div className="dp-help-content"><Truck size={28}/><p>This prototype uses three sample Pune areas and simulated monthly revenue. The coverage map is illustrative.</p><p>Saved fees stay on this browser and do not change advertiser prices, send commands to delivery boxes, or move money.</p><p>The next integration points are partner authentication, fleet and restaurant data, verified revenue, and server-side pricing.</p></div></DialogContent></Dialog></div>;
}
export function PartnerShell({children}:{children:React.ReactNode}) {return <PartnerProvider><Inner>{children}</Inner></PartnerProvider>;}
